# Validate GPT results using pattern matching

In [1]:
import json
import pandas as pd
import re

## Processed GPT Text Data

In [2]:
gpt_data_paths = {
    'kaggle': '/Users/hadleydixon/Desktop/gamification_data_analysis/Data/kaggle_results/all_processed_kaggle.json',
    'aicrowd': '/Users/hadleydixon/Desktop/gamification_data_analysis/Data/aicrowd_results/all_processed_aicrowd.json',
    'drivendata': '/Users/hadleydixon/Desktop/gamification_data_analysis/Data/drivendata_results/all_processed_drivendata.json'
}

In [3]:
processed_gpt_results = {}
for platform, path in gpt_data_paths.items():
    try:
        with open(path, 'r', encoding='utf-8') as f:
            processed_gpt_results[platform] = json.load(f)
        print(f"Loaded {len(processed_gpt_results[platform])} processed results from {platform}")
    except FileNotFoundError:
        print(f"Warning: {path} not found")
    except json.JSONDecodeError:
        print(f"Warning: Error parsing JSON from {path}")

Loaded 300 processed results from kaggle
Loaded 221 processed results from aicrowd
Loaded 65 processed results from drivendata

In [4]:
processed_gpt_dfs = {}
for platform, data in processed_gpt_results.items():
    if data:
        processed_gpt_dfs[platform] = pd.DataFrame(data)
        print(f"Created DataFrame for {platform} with {len(processed_gpt_dfs[platform])} rows")

Created DataFrame for kaggle with 300 rows
Created DataFrame for aicrowd with 221 rows
Created DataFrame for drivendata with 65 rows

## Processed Pattern Matching

In [5]:
pattern_match_paths = {
    'kaggle': '/Users/hadleydixon/Desktop/gamification_data_analysis/Data/kaggle_results/all_pattern_match_results.json',
    'aicrowd': '/Users/hadleydixon/Desktop/gamification_data_analysis/Data/aicrowd_results/all_pattern_match_results.json',
    'drivendata': '/Users/hadleydixon/Desktop/gamification_data_analysis/Data/drivendata_results/all_pattern_match_results.json'
}

In [6]:
pattern_match_results = {}
for platform, path in pattern_match_paths.items():
    try:
        with open(path, 'r', encoding='utf-8') as f:
            pattern_match_results[platform] = json.load(f)
        print(f"Loaded {len(pattern_match_results[platform])} processed results from {platform}")
    except FileNotFoundError:
        print(f"Warning: {path} not found")
    except json.JSONDecodeError:
        print(f"Warning: Error parsing JSON from {path}")

Loaded 300 processed results from kaggle
Loaded 221 processed results from aicrowd
Loaded 65 processed results from drivendata

In [7]:
pattern_match_dfs = {}
for platform, data in pattern_match_results.items():
    if data:
        pattern_match_dfs[platform] = pd.DataFrame(data)
        print(f"Created DataFrame for {platform} with {len(pattern_match_dfs[platform])} rows")

Created DataFrame for kaggle with 300 rows
Created DataFrame for aicrowd with 221 rows
Created DataFrame for drivendata with 65 rows

In [8]:
pattern_match_dfs["kaggle"].head()

,name,url,fairness_bias_mentioned,how_fairness,data_privacy,how_data_privacy,toy,how_toy,red_team,how_red_team,transparency_mentioned,how_transparency
0,CPROD1: Consumer PRODucts contest #1,https://www.kaggle.com/competitions/cprod1,no,n/a,no,n/a,yes,"example, sample",no,n/a,no,n/a
1,EMC Israel Data Science Challenge,https://www.kaggle.com/competitions/emc-data-s...,no,n/a,no,n/a,no,n/a,no,n/a,no,n/a
2,Practice Fusion Diabetes Classification,https://www.kaggle.com/competitions/pf2012-dia...,no,n/a,yes,de-identified,yes,"starter, practice",no,n/a,no,n/a
3,Detecting Insults in Social Commentary,https://www.kaggle.com/competitions/detecting-...,no,n/a,no,n/a,no,n/a,no,n/a,no,n/a
4,Cause-effect pairs,https://www.kaggle.com/competitions/cause-effe...,yes,bias,no,n/a,yes,sample,no,n/a,no,n/a

In [9]:
processed_gpt_dfs["kaggle"].head()

,category,fairness_bias_mentioned,how_fairness,data_privacy,how_data_privacy,toy,red_team,transparency_mentioned,how_transparency,name,url
0,Natural Language Processing,no,n/a,no,n/a,no,no,no,n/a,CPROD1: Consumer PRODucts contest #1,https://www.kaggle.com/competitions/cprod1
1,Data Science,no,n/a,no,n/a,no,no,no,n/a,EMC Israel Data Science Challenge,https://www.kaggle.com/competitions/emc-data-s...
2,Healthcare,no,n/a,yes,The data involves de-identified medical record...,no,no,no,n/a: The competition emphasizes a random fores...,Practice Fusion Diabetes Classification,https://www.kaggle.com/competitions/pf2012-dia...
3,Natural Language Processing,no,n/a,yes,Potential privacy issues due to publicly sourc...,no,no,no,"n/a, the competition focuses on single-class c...",Detecting Insults in Social Commentary,https://www.kaggle.com/competitions/detecting-...
4,Data Science and Machine Learning,yes,Normalization and quantization were adjusted t...,no,n/a,no,no,no,"n/a, focus is on ranking cause-effect pairs fo...",Cause-effect pairs,https://www.kaggle.com/competitions/cause-effe...

## Align Entries

In [10]:
gpt_kaggle_df = processed_gpt_dfs["kaggle"]
gpt_aicrowd_df = processed_gpt_dfs["aicrowd"]
gpt_drivendata_df = processed_gpt_dfs["drivendata"]

pattern_kaggle_df = pattern_match_dfs["kaggle"]
pattern_aicrowd_df = pattern_match_dfs["aicrowd"]
pattern_drivendata_df = pattern_match_dfs["drivendata"]

In [11]:
kaggle_merged_df = pd.merge(
    gpt_kaggle_df, pattern_kaggle_df,
    on='url',
    suffixes=('_gpt', '_pattern')
)

aicrowd_merged_df = pd.merge(
    gpt_aicrowd_df, pattern_aicrowd_df,
    on='url',
    suffixes=('_gpt', '_pattern')
)

drivendata_merged_df = pd.merge(
    gpt_drivendata_df, pattern_drivendata_df,
    on='url',
    suffixes=('_gpt', '_pattern')
)

## Compare Fields

### Kaggle

In [12]:
kaggle_merged_df.head()

,category,fairness_bias_mentioned_gpt,how_fairness_gpt,data_privacy_gpt,how_data_privacy_gpt,toy_gpt,red_team_gpt,transparency_mentioned_gpt,how_transparency_gpt,name_gpt,...,fairness_bias_mentioned_pattern,how_fairness_pattern,data_privacy_pattern,how_data_privacy_pattern,toy_pattern,how_toy,red_team_pattern,how_red_team,transparency_mentioned_pattern,how_transparency_pattern
0,Natural Language Processing,no,n/a,no,n/a,no,no,no,n/a,CPROD1: Consumer PRODucts contest #1,...,no,n/a,no,n/a,yes,"example, sample",no,n/a,no,n/a
1,Data Science,no,n/a,no,n/a,no,no,no,n/a,EMC Israel Data Science Challenge,...,no,n/a,no,n/a,no,n/a,no,n/a,no,n/a
2,Healthcare,no,n/a,yes,The data involves de-identified medical record...,no,no,no,n/a: The competition emphasizes a random fores...,Practice Fusion Diabetes Classification,...,no,n/a,yes,de-identified,yes,"starter, practice",no,n/a,no,n/a
3,Natural Language Processing,no,n/a,yes,Potential privacy issues due to publicly sourc...,no,no,no,"n/a, the competition focuses on single-class c...",Detecting Insults in Social Commentary,...,no,n/a,no,n/a,no,n/a,no,n/a,no,n/a
4,Data Science and Machine Learning,yes,Normalization and quantization were adjusted t...,no,n/a,no,no,no,"n/a, focus is on ranking cause-effect pairs fo...",Cause-effect pairs,...,yes,bias,no,n/a,yes,sample,no,n/a,no,n/a

In [13]:
fields = ['fairness_bias_mentioned', 'data_privacy', 'toy', 'red_team', 'transparency_mentioned']

for field in fields:
    gpt_col = f"{field}_gpt"
    pattern_col = f"{field}_pattern"
    match_col = f"{field}_match"
    
    kaggle_merged_df[match_col] = kaggle_merged_df[gpt_col] == kaggle_merged_df[pattern_col]

In [15]:
def manually_adjust_column(i_list, col, update, ethic_field, platform_df):
    for i in i_list:
        platform_df.loc[i, col] = update
        platform_df.loc[i, ethic_field] = True

#### Bias & Fairness - Done

In [47]:
pd.set_option('display.max_colwidth', None)
kaggle_merged_df[kaggle_merged_df["fairness_bias_mentioned_match"] == False][["fairness_bias_mentioned_gpt","how_fairness_gpt","fairness_bias_mentioned_pattern", "how_fairness_pattern", "url"]]

Empty DataFrame
Columns: [fairness_bias_mentioned_gpt, how_fairness_gpt, fairness_bias_mentioned_pattern, how_fairness_pattern, url]
Index: []

In [17]:
kaggle_bias_pattern_no_idx = [11,12,15,34,41,63,124,193]
manually_adjust_column(kaggle_bias_pattern_no_idx, 'fairness_bias_mentioned_pattern', "no - MA", 'fairness_bias_mentioned_match', kaggle_merged_df)

kaggle_bias_pattern_yes_idx = [138,139]
manually_adjust_column(kaggle_bias_pattern_yes_idx, 'fairness_bias_mentioned_pattern', "yes - MA", 'fairness_bias_mentioned_match', kaggle_merged_df)

kaggle_bias_gpt_no_idx = [127,199]
manually_adjust_column(kaggle_bias_gpt_no_idx, 'fairness_bias_mentioned_gpt', "no - MA", 'fairness_bias_mentioned_match', kaggle_merged_df)

kaggle_bias_gpt_yes_idx = [56]
manually_adjust_column(kaggle_bias_gpt_yes_idx, 'fairness_bias_mentioned_gpt', "yes - MA", 'fairness_bias_mentioned_match', kaggle_merged_df)

#### Data Privacy - Done

In [22]:
kaggle_privacy_discrepencies = kaggle_merged_df[kaggle_merged_df["data_privacy_match"] == False][["data_privacy_gpt", "how_data_privacy_gpt", "data_privacy_pattern","how_data_privacy_pattern", "url"]]
kaggle_privacy_discrepencies

Empty DataFrame
Columns: [data_privacy_gpt, how_data_privacy_gpt, data_privacy_pattern, how_data_privacy_pattern, url]
Index: []

In [20]:
kaggle_privacy_indexes = kaggle_merged_df[kaggle_merged_df["data_privacy_match"] == False].index
kaggle_privacy_index_list = list(kaggle_privacy_indexes)

In [21]:
manually_adjust_column(kaggle_privacy_index_list, 'data_privacy_pattern', "yes - MA", 'data_privacy_match', kaggle_merged_df)

#### Red Team - Done

In [25]:
kaggle_red_team_discrepencies = kaggle_merged_df[kaggle_merged_df["red_team_match"] == False][["red_team_gpt", "red_team_pattern", "how_red_team", "url"]]
kaggle_red_team_discrepencies

Empty DataFrame
Columns: [red_team_gpt, red_team_pattern, how_red_team, url]
Index: []

In [24]:
kaggle_red_pattern_no_idx = [20,45,87,175]
manually_adjust_column(kaggle_red_pattern_no_idx, 'red_team_pattern', "no - MA", 'red_team_match', kaggle_merged_df)

#### Toy - TBD

In [61]:
(kaggle_merged_df == False).sum()
# kaggle_merged_df.columns

category                             0
fairness_bias_mentioned_gpt          0
how_fairness_gpt                     0
data_privacy_gpt                     0
how_data_privacy_gpt                 0
toy_gpt                              0
red_team_gpt                         0
transparency_mentioned_gpt           0
how_transparency_gpt                 0
name_gpt                             0
url                                  0
name_pattern                         0
fairness_bias_mentioned_pattern      0
how_fairness_pattern                 0
data_privacy_pattern                 0
how_data_privacy_pattern             0
toy_pattern                          0
how_toy                              0
red_team_pattern                     0
how_red_team                         0
transparency_mentioned_pattern       0
how_transparency_pattern             0
fairness_bias_mentioned_match        0
data_privacy_match                   0
toy_match                          124
red_team_match                       0
transparency_mentioned_match         0
dtype: int64

In [27]:
# TBD
kaggle_merged_df.loc[0, 'toy_pattern'] = "no - MA"
kaggle_merged_df.loc[0, 'toy_match'] = True

kaggle_merged_df.loc[2, 'toy_pattern'] = "no - MA"
kaggle_merged_df.loc[2, 'toy_match'] = True

In [28]:
kaggle_toy_discrepencies = kaggle_merged_df[kaggle_merged_df["toy_match"] == False][["toy_gpt", "toy_pattern", "how_toy", "url"]]
kaggle_toy_discrepencies

,toy_gpt,toy_pattern,how_toy,url
4,no,yes,sample,https://www.kaggle.com/competitions/cause-effect-pairs
5,no,yes,"learning, practice",https://www.kaggle.com/competitions/multi-modal-gesture-recognition
6,no,yes,example,https://www.kaggle.com/competitions/loan-default-prediction
7,no,yes,example,https://www.kaggle.com/competitions/grasp-and-lift-eeg-detection
9,no,yes,"learning, educational, sample",https://www.kaggle.com/competitions/bengaliai-cv19
...,...,...,...,...
277,yes,no,n/a,https://www.kaggle.com/competitions/hashcode-2021-oqr-extension
278,no,yes,"starter, example",https://www.kaggle.com/competitions/phase-ii-widsdatathon2022
279,yes,no,n/a,https://www.kaggle.com/competitions/llm-prompting-with-makersuite
292,no,yes,"starter, learning, tutorial",https://www.kaggle.com/competitions/donorschoose-application-screening
297,no,yes,"starter, learning, playground, example",https://www.kaggle.com/competitions/flavours-of-physics-kernels-only

#### Transparency & Interpretability - Done

In [31]:
kaggle_transparency_discrepencies = kaggle_merged_df[kaggle_merged_df["transparency_mentioned_match"] == False][["transparency_mentioned_gpt", "how_transparency_gpt", "transparency_mentioned_pattern", "how_transparency_pattern", "url"]]
kaggle_transparency_discrepencies

Empty DataFrame
Columns: [transparency_mentioned_gpt, how_transparency_gpt, transparency_mentioned_pattern, how_transparency_pattern, url]
Index: []

In [30]:
kaggle_transparency_pattern_no_idx = [31,50,51,87]
manually_adjust_column(kaggle_transparency_pattern_no_idx, 'transparency_mentioned_pattern', "no - MA", 'transparency_mentioned_match', kaggle_merged_df)

kaggle_transparency_pattern_yes_idx = [77]
manually_adjust_column(kaggle_transparency_pattern_yes_idx, 'transparency_mentioned_pattern', "yes - MA", 'transparency_mentioned_match', kaggle_merged_df)

kaggle_transparency_gpt_no_idx = [41]
manually_adjust_column(kaggle_transparency_gpt_no_idx, 'transparency_mentioned_gpt', "no - MA", 'transparency_mentioned_match', kaggle_merged_df)

### AICrowd

In [32]:
for field in fields:
    gpt_col = f"{field}_gpt"
    pattern_col = f"{field}_pattern"
    match_col = f"{field}_match"
    
    aicrowd_merged_df[match_col] = aicrowd_merged_df[gpt_col] == aicrowd_merged_df[pattern_col]

#### Fairness & Bias - Done

In [33]:
aicrowd_bias_pattern_yes_idx = [13,54,66,87,95,104,105]
manually_adjust_column(aicrowd_bias_pattern_yes_idx, 'fairness_bias_mentioned_pattern', "yes - MA", 'fairness_bias_mentioned_match', aicrowd_merged_df)

aicrowd_bias_gpt_no_idx = [0]
manually_adjust_column(aicrowd_bias_gpt_no_idx, 'fairness_bias_mentioned_gpt', "no - MA", 'fairness_bias_mentioned_match', aicrowd_merged_df)

In [34]:
pd.set_option('display.max_colwidth', None)
aicrowd_merged_df[aicrowd_merged_df["fairness_bias_mentioned_match"] == False][["fairness_bias_mentioned_gpt","how_fairness_gpt","fairness_bias_mentioned_pattern", "how_fairness_pattern", "url"]]

Empty DataFrame
Columns: [fairness_bias_mentioned_gpt, how_fairness_gpt, fairness_bias_mentioned_pattern, how_fairness_pattern, url]
Index: []

#### Data Privacy - Done

In [42]:
aicrowd_merged_df[aicrowd_merged_df["data_privacy_match"] == False][["data_privacy_gpt","how_data_privacy_gpt","data_privacy_pattern", "how_data_privacy_pattern", "url"]]

Empty DataFrame
Columns: [data_privacy_gpt, how_data_privacy_gpt, data_privacy_pattern, how_data_privacy_pattern, url]
Index: []

In [39]:
aicrowd_privacy_indexes = aicrowd_merged_df[aicrowd_merged_df["data_privacy_match"] == False].index
aicrowd_privacy_index_list = list(aicrowd_privacy_indexes)

In [41]:
manually_adjust_column(aicrowd_privacy_index_list, 'data_privacy_pattern', "yes - MA", 'data_privacy_match', aicrowd_merged_df)

#### Red Team - Done

In [45]:
pd.set_option('display.max_colwidth', None)
aicrowd_merged_df[aicrowd_merged_df["red_team_match"] == False][["red_team_gpt","red_team_pattern","how_red_team", "url"]]

Empty DataFrame
Columns: [red_team_gpt, red_team_pattern, how_red_team, url]
Index: []

In [44]:
aicrowd_red_pattern_no_idx = []
manually_adjust_column(aicrowd_red_pattern_no_idx, 'red_team_pattern', "no - MA", 'red_team_match', aicrowd_merged_df)

aicrowd_red_pattern_yes_idx = [11]
manually_adjust_column(aicrowd_red_pattern_yes_idx, 'red_team_pattern', "yes - MA", 'red_team_match', aicrowd_merged_df)

aicrowd_red_gpt_no_idx = [170,234]
manually_adjust_column(aicrowd_red_gpt_no_idx, 'red_team_gpt', "no - MA", 'red_team_match', aicrowd_merged_df)

aicrowd_red_gpt_yes_idx = []
manually_adjust_column(aicrowd_red_gpt_yes_idx, 'red_team_gpt', "yes - MA", 'red_team_match', aicrowd_merged_df)

#### Toy - TBD

In [62]:
(aicrowd_merged_df == False).sum()
# aicrowd_merged_df.columns

category                            0
fairness_bias_mentioned_gpt         0
how_fairness_gpt                    0
data_privacy_gpt                    0
how_data_privacy_gpt                0
toy_gpt                             0
red_team_gpt                        0
transparency_mentioned_gpt          0
how_transparency_gpt                0
url                                 0
name                                0
fairness_bias_mentioned_pattern     0
how_fairness_pattern                0
data_privacy_pattern                0
how_data_privacy_pattern            0
toy_pattern                         0
how_toy                             0
red_team_pattern                    0
how_red_team                        0
transparency_mentioned_pattern      0
how_transparency_pattern            0
fairness_bias_mentioned_match       0
data_privacy_match                  0
toy_match                          98
red_team_match                      0
transparency_mentioned_match        0
dtype: int64

#### Interpretability & Transparency - DONE

In [58]:
aicrowd_transparency_pattern_no_idx = []
manually_adjust_column(aicrowd_transparency_pattern_no_idx, 'transparency_mentioned_pattern', "no - MA", 'transparency_mentioned_match', aicrowd_merged_df)

aicrowd_transparency_pattern_yes_idx = [0,2,3,6,7,10,87,79,106,94]
manually_adjust_column(aicrowd_transparency_pattern_yes_idx, 'transparency_mentioned_pattern', "yes - MA", 'transparency_mentioned_match', aicrowd_merged_df)

aicrowd_transparency_gpt_no_idx = [67]
manually_adjust_column(aicrowd_transparency_gpt_no_idx, 'transparency_mentioned_gpt', "no - MA", 'transparency_mentioned_match', aicrowd_merged_df)

aicrowd_transparency_gpt_yes_idx = []
manually_adjust_column(aicrowd_transparency_gpt_yes_idx, 'transparency_mentioned_gpt', "yes - MA", 'transparency_mentioned_match', aicrowd_merged_df)

In [59]:
pd.set_option('display.max_colwidth', None)
aicrowd_merged_df[aicrowd_merged_df["transparency_mentioned_match"] == False][["transparency_mentioned_gpt","how_transparency_gpt","transparency_mentioned_pattern", "how_transparency_pattern","url"]]

Empty DataFrame
Columns: [transparency_mentioned_gpt, how_transparency_gpt, transparency_mentioned_pattern, how_transparency_pattern, url]
Index: []

### DrivenData

In [66]:
for field in fields:
    gpt_col = f"{field}_gpt"
    pattern_col = f"{field}_pattern"
    match_col = f"{field}_match"
    
    drivendata_merged_df[match_col] = drivendata_merged_df[gpt_col] == drivendata_merged_df[pattern_col]

In [74]:
(drivendata_merged_df == False).sum()

category                                0
fairness_bias_mentioned_gpt             0
how_fairness_gpt                        0
data_privacy_gpt                        0
how_data_privacy_gpt                    0
toy_gpt                                 0
red_team_gpt                            0
transparency_mentioned_gpt              0
how_transparency_gpt                    0
url                                     0
name                                    0
fairness_bias_mentioned_pattern         0
how_fairness_pattern                    0
data_privacy_pattern                    0
how_data_privacy_pattern                0
toy_pattern                             0
how_toy                                 0
red_team_pattern                        0
how_red_team                            0
transparency_mentioned_pattern          0
how_transparency_pattern                0
fairness_bias_mentioned_discrepency     5
data_privacy_discrepency               35
toy_discrepency                        14
red_team_discrepency                   11
transparency_mentioned_discrepency      9
fairness_bias_mentioned_match           5
data_privacy_match                      0
toy_match                              14
red_team_match                         11
transparency_mentioned_match            9
dtype: int64

In [68]:
drivendata_merged_df.columns

Index(['category', 'fairness_bias_mentioned_gpt', 'how_fairness_gpt',
       'data_privacy_gpt', 'how_data_privacy_gpt', 'toy_gpt', 'red_team_gpt',
       'transparency_mentioned_gpt', 'how_transparency_gpt', 'url', 'name',
       'fairness_bias_mentioned_pattern', 'how_fairness_pattern',
       'data_privacy_pattern', 'how_data_privacy_pattern', 'toy_pattern',
       'how_toy', 'red_team_pattern', 'how_red_team',
       'transparency_mentioned_pattern', 'how_transparency_pattern',
       'fairness_bias_mentioned_discrepency', 'data_privacy_discrepency',
       'toy_discrepency', 'red_team_discrepency',
       'transparency_mentioned_discrepency', 'fairness_bias_mentioned_match',
       'data_privacy_match', 'toy_match', 'red_team_match',
       'transparency_mentioned_match'],
      dtype='object')

#### Bias & Fairness - TBD

In [ ]:
drivendata_merged_df[drivendata_merged_df["fairness_bias_mentioned_match"] == False][["fairness_bias_mentioned_gpt","how_fairness_gpt","fairness_bias_mentioned_pattern", "how_fairness_pattern","url"]]

,fairness_bias_mentioned_gpt,how_fairness_gpt,fairness_bias_mentioned_pattern,how_fairness_pattern,url,name
6,yes,The competition aims to improve accuracy across diverse populations and explore understudied factors indicating early AD/ADRD.,no,n/a,https://www.drivendata.org/competitions/304/prepare-challenge-phase-3/,
7,yes,"The competition aims to improve prediction accuracy across diverse populations and address bias, especially for underrepresented groups.",no,n/a,https://www.drivendata.org/competitions/299/competition-nih-alzheimers-acoustic-2/,
8,yes,Special Recognition Prizes include categories like best consideration of bias and potential to generalize to populations disproportionately impacted by AD/ADRD.,no,n/a,https://www.drivendata.org/competitions/300/competition-nih-alzheimers-sdoh-2/,
9,yes,The competition seeks to improve AD/ADRD prediction accuracy across diverse populations and specifically mentions addressing bias in model development.,no,n/a,https://www.drivendata.org/competitions/301/prepare-challenge-phase-2-report-arena/,
10,yes,The competition aims to address racial and ethnic disparities in AD/ADRD diagnosis and emphasizes data from underrepresented groups.,no,n/a,https://www.drivendata.org/competitions/253/competition-nih-alzheimers-adrd-1/,

In [ ]:
drivendata_bias_pattern_no_idx = []
manually_adjust_column(drivendata_bias_pattern_no_idx, 'fairness_bias_mentioned_pattern', "no - MA", 'fairness_bias_mentioned_match', drivendata_merged_df)

drivendata_bias_pattern_yes_idx = [6]
manually_adjust_column(drivendata_bias_pattern_yes_idx, 'fairness_bias_mentioned_pattern', "yes - MA", 'fairness_bias_mentioned_match', drivendata_merged_df)

drivendata_bias_gpt_no_idx = []
manually_adjust_column(drivendata_bias_gpt_no_idx, 'fairness_bias_mentioned_gpt', "no - MA", 'fairness_bias_mentioned_match', drivendata_merged_df)

drivendata_bias_gpt_yes_idx = []
manually_adjust_column(drivendata_bias_gpt_yes_idx, 'fairness_bias_mentioned_gpt', "yes - MA", 'fairness_bias_mentioned_match', drivendata_merged_df)

#### Data Privacy - DONE

In [71]:
drivendata_privacy_indexes = drivendata_merged_df[drivendata_merged_df["data_privacy_match"] == False].index
drivendata_privacy_index_list = list(drivendata_privacy_indexes)

In [72]:
manually_adjust_column(drivendata_privacy_index_list, 'data_privacy_pattern', "yes - MA", 'data_privacy_match', drivendata_merged_df)

In [73]:
drivendata_merged_df[drivendata_merged_df["data_privacy_match"] == False][["data_privacy_gpt","how_data_privacy_gpt","data_privacy_pattern", "how_data_privacy_pattern","url"]]

Empty DataFrame
Columns: [data_privacy_gpt, how_data_privacy_gpt, data_privacy_pattern, how_data_privacy_pattern, url]
Index: []

#### Red - TBD

#### Toy - TBD

#### Interpretability & Transparency - TBD